language: cpp
dist: focal
sudo: false
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - gcc-10
            - g++-10
      env:
        - C_COMPILER=gcc-10
        - CXX_COMPILER=g++-10
        - CXX_FLAGS=""
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-11
            - libc++-11-dev
            - libc++abi-11-dev
      env:
        - C_COMPILER=clang-11
        - CXX_COMPILER=clang++-11
        - CXX_FLAGS="-stdlib=libc++"
script:
  - cmake -S . -B build
    -DGRAM_BUILD_TESTS=ON
    -DCMAKE_C_COMPILER=$C_COMPILER
    -DCMAKE_CXX_COMPILER=$CXX_COMPILER
    -DCMAKE_CXX_FLAGS=$CXX_FLAGS
  - cmake --build build
  - ./build/test/unit/utest
  - ./build/test/acceptance/atest
