language: cpp
dist: trusty
sudo: false
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env:
        - C_COMPILER=gcc-6
        - CXX_COMPILER=g++-6
        - CXX_FLAGS=""
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libc++-dev
      env:
        - C_COMPILER=clang-4.0
        - CXX_COMPILER=clang++-4.0
        - CXX_FLAGS="-stdlib=libc++"
script:
  - mkdir build
  - cd build
  - cmake ..
    -DGRAM_BUILD_TESTS=ON
    -DCMAKE_C_COMPILER=$C_COMPILER
    -DCMAKE_CXX_COMPILER=$CXX_COMPILER
    -DCMAKE_CXX_FLAGS=$CXX_FLAGS
  - make
  - ./test/unit/utest
  - ./test/acceptance/atest
